### ISSUE TITLE
您好，无法创建目录

### ISSUE THREAD

**Issue by WystanW** [fangyuzhong2016/HadoopIntellijPlugin#1]
本地用虚拟机建立了一个主节点，然后在主节点这个虚拟机中用docker建立了三个三个从节点，在windows下开发的，上传文件结果是成功的但是显示上传失败，创建目录无法创建，不报错，只是无法创建。我的hdfs默认应该是谁都可以访问的，想知道连接的时候那个用户应该怎么写呢？

**Comment by fangyuzhong2016** [comment]
看样子，你的配置界面，默认的用户名称好像没有啊，连接的时候 是读取操作系统的默认的用户的。，源码中在读取配置权限的时候好像也没判断用户名为空的情况，也许是个BUG....额.......如果可能，最好把代码下载下来，构建调试环境，然后跟踪。权限代码在..../com/fangyuzhong/intellij/hadoop/core/hadoop/HDFUtil 类的 getDirFileActionByUser 方法

**Comment by WystanW** [comment]
谢谢，插件非常好用

**Comment by fangyuzhong2016** [comment]
谢谢，共同交流学习

**Comment by bk201sama** [comment]
2.6 版本的编译失败，主要是getDirFileActionByUser方法

**Comment by fangyuzhong2016** [comment]
getDirFileActionByUser 是关于权限这块的，得看下2.6版本的包是否支持这个方法中的代码，该方法是基于3.0版本写的，2.6并未测试

**Comment by fangyuzhong2016** [comment]
用户权限的问题，当Hadoop集群没有开启ACL的权限认证，即Hadoop集群对任何用户都有默认的访问创建等权限，连接到HDFS客户端默认先查找ACL认证，没有的话读取系统的环境变量，查找key是HADOOP_USER_NAME 有没有值，如果没有，再查找Java的环境变量，查找HADOOP_USER_NAME值有没有，如果还是没有 ，读取操作系统的登录账户，作为HDFS客户端连接到HDFS的用户，因此连接设置中，默认创建了一个Java的系统环境变量，HADOOP_USER_NAME  值是配置界面输入的用户名称，该名称需要和HDFS集群中的文件系统所有者对应，该BUG已经解决！
