### ISSUE TITLE
打开项目时如果没有hadoop环境，项目打开超慢

### ISSUE THREAD

**Issue by guo156627977** [fangyuzhong2016/HadoopIntellijPlugin#2]
打开已经配置插件的项目时如果没有对应的hadoop环境，idea打开超极慢

**Comment by fangyuzhong2016** [comment]
是的，这是个BUG，在没有Hadoop环境中，初始化idea 打开项目，他会去链接Hadoop，直到链接超时，如果hadoop 没有启动，变得很慢，这个由于时间的关系 ，BUG还没解决。如果你那边有空，也可以跟踪源码，尝试解决，提交BUG

**Comment by fangyuzhong2016** [comment]
没有Hadoop环境，或者Hadoop集群连接不上，打开带有插件配置的项目时，卡死，Hadoop连接到集群，默认配置IPC连接10秒超时，重试45次，会卡460s 左右，插件在开发时，采用了默认的配置，现在已经修改为IPC连接3秒超时，重试1次，会卡6—7 S，该BUG已经解决
